### ISSUE TITLE
climate trash-size and empty-trash not see the ~/.local/share/Trash

### ISSUE THREAD

**Issue by hong-duc** [adtac/climate#15]
when i run `climate trash-size` and `empty-trash` it throw error `Error: Unable to find trash size. Check if ~/.local/share/Trash exists.`. But i have checked and i have the Trash folder in `~/.local/share/Trash`

My linux is Debian 8.6 jessie

**Comment by adtac** [comment]
@hong-duc thanks for filing the issue. Just fixed :+1:

Please udate with `sudo climate update` and try again.
