### ISSUE TITLE
error climate is-up

### ISSUE THREAD

**Issue by Oxicode** [adtac/climate#17]
![image](https://cloud.githubusercontent.com/assets/1320709/20895075/f84f69e8-bae5-11e6-8342-d6becd9e0021.png)

**Comment by Oxicode** [comment]
Mi instalación 
![image](https://cloud.githubusercontent.com/assets/1320709/20895095/055d92ea-bae6-11e6-8c29-e2cfd351a3c6.png)

**Comment by adtac** [comment]
@Oxicode please try without the `http://` before the domain name. `climate is-up oxicode.io` works for me.

**Comment by Oxicode** [comment]
![image](https://cloud.githubusercontent.com/assets/1320709/20895800/dc86a2aa-bae8-11e6-9720-e0c247c673f2.png)

**Comment by adtac** [comment]
Can you run the install again and post the output? I think `npm` is not installing all dependencies for some reason.

If not, you can try `npm install -g is-up-cli`

**Comment by Oxicode** [comment]
![image](https://cloud.githubusercontent.com/assets/1320709/20896162/6ce5217c-baea-11e6-80bd-1ba0830ff404.png)

**Comment by nickpolet** [comment]
I get the same error as @Oxicode as well. Running `npm install -g is-up-cli` doesn't fix the issue either. I'm running a fresh Ubuntu 16.04 install, so there shouldn't be any npm issues.

**Comment by adtac** [comment]
@Oxicode @nickpolet could you try the install again with the latest version? I spawned up a fresh Ubuntu 16.04 VM and tested the install (from the current master; I added a couple of commits) and it worked.

**Comment by Oxicode** [comment]
Is Ok, thx
![image](https://cloud.githubusercontent.com/assets/1320709/20988120/5b88f520-bc9d-11e6-942e-4a03fceb9b6f.png)

**Comment by adtac** [comment]
Great! :)

@nickpolet could you confirm as well?
