### ISSUE TITLE
Add autocomplete for fish

### ISSUE THREAD

**Issue by Hunsu** [adtac/climate#20]
I can do it. I will first look on how I could do it with dynamic autocomplete.

**Comment by adtac** [comment]
@Hunsu hey! Sorry for the really late reply - I probably missed the notification.

And yes, autocomplete for fish would be lovely :) Looking forward to it. (Assigning you this issue.)

**Comment by Hunsu** [comment]
Submitted a PR to the fish project https://github.com/fish-shell/fish-shell/pull/3760

**Comment by adtac** [comment]
Huh, didn't know that fish had a centralized repo for all completions :)

Anyway, thanks a lot for the patch there! Feel free to close this issue when you get it merged it there.

**Comment by Hunsu** [comment]
https://github.com/fish-shell/fish-shell/commit/a5e8b81ee34ecc5bd19114c2079a3fff196e6a10

**Comment by adtac** [comment]
Nice, thanks!
