### ISSUE TITLE
climate didn't warn me it will install a lot of crap

### ISSUE THREAD

**Issue by ghost** [adtac/climate#27]
````

 • upower exists!
 • curl exists!
 • rar missing. Installing... Installed!
 • unzip exists!
 • 7z missing. Installing... Installed!
 • xdg-screensaver exists!
 • dig exists!
 • git exists!
 • python exists!
 • pip missing. Installing... Installed!
 • node missing. Installing... Installed!
 • npm missing. Installing... Installed!
 • fdupes missing. Installing... Installed!
 • glances missing. Installing... Installed!
 • sensors exists!
 • sshfs missing. Installing... Installed!
 • gawk missing. Installing... Installed!
 • jq missing. Installing... Installed!
 • http-server missing. Installing... Installed!
 • is-up missing. Installing... Installed!
 • is-online missing. Installing... Installed!
 • speedtest missing. Installing... Installed!
 • httpstat missing. Installing... Installed!
````

I DIDN'T NEED that. How to uninstall all of that?   
````
sudo apt-get purge node
`````          
doesn't work

**Comment by ghost** [comment]
why I can not delete any of these with apt-get?
How to clean up my system?
How to revert all dat installed apps?

**Comment by adtac** [comment]
Just uninstall them manually. The list of dependencies is clearly mentioned in the README.

**Comment by ghost** [comment]
does these software creates more than a binary in few directories?
apt-get doesn't want uninstall them, it says there's no such packages like node, npm, pip, etc.

**Comment by adtac** [comment]
Uh that should not happen. Are you sure `npm` is even installed?

**Comment by ghost** [comment]
I didn't have <kbd>npm</kbd> before climate. I am sure that <kbd>sudo apt-get</kbd> remove\purge didn't want to uninstall stuff. Any. I can run binaries but aptitude says it's not in the system. So I deleted everything manually, I am sure lots of configs and other stuff left in my system and that pisses me off. I understand it was my fault, shouldn't copypaste everything I see in the internet into the terminal :rage: 

Hate all that dependency shit in unix like systems. 

I can not get one thing why climate is better than simple bash.src file? What made me try it? Meh... :man_facepalming:
