### ISSUE TITLE
Add the command auto-completion could be better.

### ISSUE THREAD

**Issue by leozhang2018** [adtac/climate#4]
There is no auto-completion in this  version,add the command auto-completion could be better.

**Comment by adtac** [comment]
Agreed, I had this in mind when designing the way commands are executed - just need to add a autocomplete command inside `shelp` now. I haven't got much experience with autocomplete however, so if someone would be generous enough to contribute a patch, I'd gladly accept it :)

**Comment by roccomuso** [comment]
cool ;) +1

**Comment by Theldus** [comment]
If by auto-complete you mean I type in the terminal for example:
climate c[TAB] and the terminal suggests me: clock and countdown, is quite easy to do and I can send you a pull request with this feature ;-).

**Comment by adtac** [comment]
@Theldus yep, that's exactly it. I'd love to get that feature merged (would improve usability by miles).

BTW would autocompletion work across multiple shells? I've tested climate in ZSH and Bash, so it'd be awesome to get this feature working in both (and possibly other shells too!).

**Comment by Theldus** [comment]
@adtac good question, yes, it is possible to work on others besides bash. In a quick test I ran on sh and zsh (with a few more lines of code).

**Comment by adtac** [comment]
I believe this is solved ;)
