### ISSUE TITLE
When trying to update

### ISSUE THREAD

**Issue by Hunsu** [adtac/climate#5]
When I type climate update I dot this:

    sh: 162: [[: not found
    sh: 166: [[: not found
    ┌───────────────────┐
    │ climate installer │
    └───────────────────┘
    sh: 180: [[: not found
    sh: 188: Bad substitution

**Comment by adtac** [comment]
@Hunsu thanks for filing this. I just fixed this.

So just for this once, you might have to manually reinstall as an update. Should work later.
