### ISSUE TITLE
Use GPL and not AGPL license

### ISSUE THREAD

**Issue by tedyoung** [adtac/climate#7]
Usually AGPL is used for applications that are only used on a server (i.e., aren't downloaded to the end user). I think AGPL is not appropriate for a shell helper tool, so this is a request to change the license to GPL (or MIT/BSD) to be friendlier to places where AGPL may not be allowed.

**Comment by adtac** [comment]
Ah, I was not aware of that. Actually, I'm not that educated with licenses. I'm a maintainer for https://github.com/coala/coala and the original author of that used AGPL. So I didn't even look into the differences used whatever they did :P

Thanks for pointing it out, I'll change it :+1: (BTW do I need to get permission from everyone who's contributed to this project to change licenses?)

**Comment by sils** [comment]
You cannot change license unless you ask every contributor AFAIK.

**Comment by adtac** [comment]
Alright, @massard-t is it alright with you if I change the license to GPL v3? (hah, that was easy, only one person to ask)

**Comment by tbobm** [comment]
Of course not, that's fine by me.

**Comment by adtac** [comment]
Great, I'll make the change :+1:
